// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Bill
    {
        public Bill()
        {
            BillDetails = new HashSet<BillDetail>();
            InverseParent = new HashSet<Bill>();
            Receipts = new HashSet<Receipt>();
        }

        public int Id { get; set; }
        public int TypeId { get; set; }
        public int ClientId { get; set; }
        public int PaymentTypeId { get; set; }
        public int? ParentId { get; set; }
        public DateTime Date { get; set; }
        public decimal Total { get; set; }
        public string Observation { get; set; }
        public bool Payoff { get; set; }
        public bool Active { get; set; }
        public DateTime CreateAt { get; set; }
        public string CreateBy { get; set; }
        public int? PaymentMethodId { get; set; }
        public int? BankId { get; set; }
        public string Reference { get; set; }

        public virtual Client Client { get; set; }
        public virtual Bill Parent { get; set; }
        public virtual BillPaymentMethod PaymentMethod { get; set; }
        public virtual BillPaymentType PaymentType { get; set; }
        public virtual BillType Type { get; set; }
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<Bill> InverseParent { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}