// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Catalog
    {
        public Catalog()
        {
            InverseParent = new HashSet<Catalog>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }

        public virtual Catalog Parent { get; set; }
        public virtual ICollection<Catalog> InverseParent { get; set; }
    }
}