// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Client
    {
        public Client()
        {
            Appointments = new HashSet<Appointment>();
            Bills = new HashSet<Bill>();
            GraduationContactLenses = new HashSet<GraduationContactLense>();
            Records = new HashSet<Record>();
            SentMessages = new HashSet<SentMessage>();
        }

        public int Id { get; set; }
        public int IdentificationTypeId { get; set; }
        public string Identification { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public DateTime? Birthdate { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneNumberWork { get; set; }
        public string CellNumber { get; set; }
        public string Correo { get; set; }
        public int? NacionalityId { get; set; }
        public int? DepartmentId { get; set; }
        public int? CityId { get; set; }
        public string Address { get; set; }
        public int? ProfessionId { get; set; }
        public string FileNumber { get; set; }
        public int? SexId { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public bool? SendNotification { get; set; }

        public virtual City City { get; set; }
        public virtual Department Department { get; set; }
        public virtual IdentificationType IdentificationType { get; set; }
        public virtual Country Nacionality { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<GraduationContactLense> GraduationContactLenses { get; set; }
        public virtual ICollection<Record> Records { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
    }
}