// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ContactLense
    {
        public int Id { get; set; }
        public int GraduationContactLensId { get; set; }
        public string Eye { get; set; }
        public string Sphere { get; set; }
        public string Cylinder { get; set; }
        public string Axis { get; set; }
        public string Diameter { get; set; }
        public string BaseCurve { get; set; }
        public string ReChange { get; set; }
        public string Convertion { get; set; }

        public virtual GraduationContactLense GraduationContactLens { get; set; }
    }
}