// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class GraduationContactLense
    {
        public GraduationContactLense()
        {
            ContactLenses = new HashSet<ContactLense>();
        }

        public int Id { get; set; }
        public int ClientId { get; set; }
        public DateTime Date { get; set; }
        public string CreateBy { get; set; }
        public DateTime? NextDateRecord { get; set; }
        public string Observation { get; set; }
        public string ResumenOd { get; set; }
        public string ResumenOi { get; set; }

        public virtual Client Client { get; set; }
        public virtual ICollection<ContactLense> ContactLenses { get; set; }
    }
}