// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class IdentificationType
    {
        public IdentificationType()
        {
            Clients = new HashSet<Client>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int StatuId { get; set; }

        public virtual Status Statu { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}