// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ItemProvider
    {
        public int ItemId { get; set; }
        public int ProviderId { get; set; }
        public DateTime ModifiedDate { get; set; }

        public virtual Item Item { get; set; }
        public virtual Provider Provider { get; set; }
    }
}