// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ItemType
    {
        public ItemType()
        {
            ItemTypeProperties = new HashSet<ItemTypeProperty>();
            Items = new HashSet<Item>();
        }

        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ItemTypeProperty> ItemTypeProperties { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}