// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ItemPrice
    {
        public int PriceId { get; set; }
        public int ItemId { get; set; }
        public decimal Price { get; set; }

        public virtual Item Item { get; set; }
    }
}