// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ItemTypeProperty
    {
        public ItemTypeProperty()
        {
            ItemPropertyValues = new HashSet<ItemPropertyValue>();
        }

        public int TypeId { get; set; }
        public int PropertyId { get; set; }

        public virtual ItemProperty Property { get; set; }
        public virtual ItemType Type { get; set; }
        public virtual ICollection<ItemPropertyValue> ItemPropertyValues { get; set; }
    }
}