// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ItemPropertyValue
    {
        public int TypeId { get; set; }
        public int ItemId { get; set; }
        public int PropertyId { get; set; }
        public string Value { get; set; }

        public virtual Item Item { get; set; }
        public virtual ItemTypeProperty ItemTypeProperty { get; set; }
    }
}