// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Item
    {
        public Item()
        {
            BillDetails = new HashSet<BillDetail>();
            ItemPrices = new HashSet<ItemPrice>();
            ItemPropertyValues = new HashSet<ItemPropertyValue>();
            ItemProviders = new HashSet<ItemProvider>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ProductNumber { get; set; }
        public int TypeId { get; set; }
        public short SafetyStockLevel { get; set; }
        public short ReorderPoint { get; set; }
        public string SizeUnitMeasureCode { get; set; }
        public string Currency { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public int Quantity { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public decimal Precio1 { get; set; }
        public decimal Precio2 { get; set; }
        public decimal Precio3 { get; set; }
        public decimal Precio4 { get; set; }
        public string Markup { get; set; }

        public virtual ItemType Type { get; set; }
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
        public virtual ICollection<ItemPropertyValue> ItemPropertyValues { get; set; }
        public virtual ICollection<ItemProvider> ItemProviders { get; set; }
    }
}