// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Prism
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public string Eye { get; set; }
        public string PrismId { get; set; }
        public string Base { get; set; }
        public string Axis { get; set; }

        public virtual Record Record { get; set; }
    }
}