// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Refraction
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public string Eye { get; set; }
        public string Sphere { get; set; }
        public string Cylinder { get; set; }
        public string Axis { get; set; }
        public string Addition { get; set; }
        public string Avsc { get; set; }
        public string Avcc { get; set; }
        public string Dpl { get; set; }
        public string Dpc { get; set; }
        public bool Transposicion { get; set; }

        public virtual Record Record { get; set; }
    }
}