// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class RolResource
    {
        public int Id { get; set; }
        public int RolId { get; set; }
        public int ResourceId { get; set; }
        public int Action { get; set; }

        public virtual Resource Resource { get; set; }
        public virtual Rol Rol { get; set; }
    }
}