// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class Status
    {
        public Status()
        {
            Doctors = new HashSet<Doctor>();
            IdentificationTypes = new HashSet<IdentificationType>();
            Vendors = new HashSet<Vendor>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<IdentificationType> IdentificationTypes { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}