// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class ToroidalContact
    {
        public decimal Sphere { get; set; }
        public decimal Cilinder { get; set; }
        public string Value { get; set; }
    }
}