// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class TwoFactorEntry
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public byte Type { get; set; }
        public string Token { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime ExpiredOn { get; set; }
        public bool Used { get; set; }

        public virtual User UserNameNavigation { get; set; }
    }
}