// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace Clinicavalle.DbModels.Clinica
{
    public partial class User
    {
        public User()
        {
            Records = new HashSet<Record>();
            TwoFactorEntries = new HashSet<TwoFactorEntry>();
        }

        public string Username { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RolId { get; set; }
        public string PhoneNumber { get; set; }
        public bool? Active { get; set; }

        public virtual Rol Rol { get; set; }
        public virtual ICollection<Record> Records { get; set; }
        public virtual ICollection<TwoFactorEntry> TwoFactorEntries { get; set; }
    }
}